### ISSUE TITLE
Enlarge font on the navigation bar

### ISSUE THREAD

**Issue by hermanp** [hermanp/website#9]
Enlarge font on the navigation bar by custom CSS.

**Comment by hermanp** [comment]
Resources (after searching for `wowchemy OR academic navbar OR navigation font`):
- [Wowchemy docs - Customization](https://wowchemy.com/docs/customization/#customize-style-css)
- [How to enlarge the navbar menu font size ? #1151](https://github.com/wowchemy/wowchemy-hugo-modules/issues/1151)

**Comment by fvlasie** [comment]
Enlarging the menu font size with CSS causes problems with width calculation. The search button will be cut off at certain window widths.

**Comment by hermanp** [comment]
Hi! Thanks for pointing it out! I have checked on these browsers, on my laptop (at 1280×800 resolution, Windows 7):
- Firefox 88: no problem
- Chrome 90: no problem
- Brave 1.23.73 (Chromium 90): no problem

![browsers](https://user-images.githubusercontent.com/16311451/116040056-cd3d7300-a66b-11eb-9cb4-9e3c56d6e719.png)
From left to right: Firefox, Chrome, Brave, seen at 450 px, 500 px and 500 px width, respectively.

Is your concern based on some theory in CSS or settings in Wowchemy? Or could you elaborate on which platform have you noticed it? What do you propose instead of the custom CSS? As I have read the Wowchemy docs, there are font size adjustments in the `params.toml` config file, but it means an overall change in size, not just on the menu bar. As I remember, I only wanted to change the menu bar font size, because I have been satisfied with the "M" size in `params.toml`.

Have a nice day!

**Comment by fvlasie** [comment]
Hello hermanp! I have noticed that, on my website, when the window is at an intermediate size (that is between full size and mobile size) the search button and half of the right-most menu item get cut off. Interestingly, I did some more testing and it seems **related to having `&nbsp;`** in the menu bar names. (I put that in there to keep the names from breaking.)

Full size:
<img width="1180" alt="Screenshot 2021-04-26 at 10 08 30 am" src="https://user-images.githubusercontent.com/33334298/116123640-1bf10a00-a678-11eb-9072-aed9e88d9dce.png">

Intermediate:
<img width="1010" alt="Screenshot 2021-04-26 at 10 08 53 am" src="https://user-images.githubusercontent.com/33334298/116123643-1d223700-a678-11eb-8fde-7deab6bf8a67.png">

Mobile:
<img width="982" alt="Screenshot 2021-04-26 at 10 09 05 am" src="https://user-images.githubusercontent.com/33334298/116123646-1dbacd80-a678-11eb-89ae-151a01a877ba.png">

**Comment by fvlasie** [comment]
A little more testing... It appears to be caused by having a menu item that is three words i.e. having two spaces. So the bug will be triggered if you have section called, in my case, "Admissions and Aid".

The bug occurs regardless of using `&nbsp;` or `white-space: nowrap`.

Having the menu item not wrap is aesthetically desirable.

Thank you Peter! Your reply helped me find the real problem.
